language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
before_install:
  - sudo apt-get install python-lxml
services:
  - elasticsearch
install:
  - python setup.py install
  - pip install flake8
script:
  - python setup.py test
  - flake8 .
